version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gantt-excel-postgres
    environment:
      POSTGRES_DB: gantt_excel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gantt-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gantt-excel-backend
    ports:
      - "9898:9898"
    environment:
      - PORT=9898
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=gantt_excel
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gantt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gantt-excel-frontend
    ports:
      - "9897:9897"
    environment:
      - VITE_API_BASE_URL=/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gantt-network

volumes:
  postgres_data:

networks:
  gantt-network:
    driver: bridge
